config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'about', to: 'pages#about', as: 'about'
  get 'programmes', to: 'pages#programmes', as: 'programmes'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def programmes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-155145533-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-155145533-1');
    </script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Awe Consulting</title>
    <%= favicon_link_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:image:width" content="1200px" />
    <meta property="og:image:height" content="630px" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />




    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Poiret+One|Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="nav">
      <ul>
<!--         <li>
          <%#= link_to 'Home', root_path, class: 'nav-link' %>
        </li> -->
        <li>
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
        <li>
          <%= link_to 'Programmes', programmes_path, class: 'nav-link' %>
        </li>
         <li>
          <%= link_to 'Contact', contact_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
    <%= yield %>
    <div class="footer d-flex justify-content-around">
      <div class="">
        <%= link_to root_path do %>
          <h1 class="footer-logo">awe</h1>
        <% end %>
      </div>
    </div>
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-banner" id="bluestairs">
</div>
<div class="container text-center text-blue paragraphs">
  <h1 class="text-blue my-4">About Us</h1>
  <h2 class="text-blue">Our Core Values</h2>
  <p><strong>awe</strong> stands for Awareness – Wellness - Engagement. We believe in the values of trust, fun and integrity.</p>
  <h2>About Us</h2>
  <p>We are a fast-growing consultancy with a passion for creativity. We guide and support clients in improving awareness on contemporary issues affecting company performance. Our clients operate in a range of industries such as insurance, sport, retail and energy. We have an extensive background in health and high-performance in sport and business. This places us at the forefront of a new frontier of understanding on the effects on health in the workplace. We believe that employee wellbeing contributes directly to your company’s bottom line. Our ideas and interventions are grounded in the latest information and research around physical wellness, health, elite team development and strategic thinking.</p>
  <h2>Our Mission</h2>
  <p>To bring a multitude of tailored programmes that can target your needs. We work with organisational leaders to identify knowledge areas that need strengthening. We believe strongly in providing high quality awareness and information transfer that commit directly to your bottom line through employee wellness. We have pride in our background in coaching and mentoring.</p>
  <h2>Why Choose us? </h2>
  <p>Clients and professionals choose awe Inspiring Consulting because of our people. We have specific expertise and experience in performance management with a background in the latest thinking and best scientific evidence around wellness and elite team performance strategies. We are all passionate, dedicated and energetic. With our knowledge base and experience we bring authenticity to our message and relevance with our approach.</p>
  <h2>What We Do.</h2>
  <p>We take themes relevant to your business – chosen by you - and we present parallels between them and the sporting world in informative, interesting awareness-building sessions for your employees, clients and stakeholders. These can be through training days involving either large group workshops, individual coaching or small-group seminars. The return on any investment to employee health and wellness can be hard to quantify, difficult to notice and hard to measure. This is why we focus on raising awareness in the knowledge and understanding of the potential professional dangers of unhealthy lifestyles as a means of futureproofing your employees.</p>
  <div class="d-flex justify-content-center">
    <%= link_to 'our programmes', programmes_path, class: 'button button-blue my-4' %>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="middle-banner mt-0" id="mountains">
  <h1>Contact Us</h1>
</div>
<div class="container text-center">
  <h3>Get in contact today for more information</h3>
  <h3 class="my-4">info@awe-inspiring-consulting.co.uk</h3>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active" id="bluestairs">
        <div class="banner-heading">
          <h1>Awareness</h1>
        </div>
      </div>
      <div class="carousel-item" id="dosomething">
        <div class="banner-heading">
          <h1>Wellness</h1>
        </div>
      </div>
      <div class="carousel-item" id="lightbulb">
        <div class="banner-heading">
          <h1>Engagement</h1>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <img src="<%= asset_path 'logo.png' %>" alt="" class='logo-home'>
</div>

<h3>Workplace Wellness - Corporate Health - Professional Lifestyle Awareness</h3>


<div class="middle-banner">
  <h1>Why Choose AWE?</h1>
</div>

<div class="home-paragraphs m-5 text-center">
  <p>
    Clients and professionals choose awe Inspiring Consulting because of our people. We have specific expertise and experience in performance management with a background in the latest thinking and best scientific evidence around wellness and elite team performance strategies. We are all passionate, dedicated and energetic. With our knowledge base and experience we bring authenticity to our message and relevance with our approach.
  </p>
  <%= link_to 'find out more', about_path, class: 'button button-blue' %>
</div>

<div class="home-programs pb-5">
  <h1 class="mb-2">Programs</h1>
  <div class="d-flex justify-content-around flex-wrap">
    <%= link_to programmes_path do %>
      <div class="home-card">
        <div class="home-card-background" id="handup">
          <div class="card-inner">
            <h3>First Step</h3>
          </div>
        </div>
      </div>
    <% end %>
    <%= link_to programmes_path do %>
      <div class="home-card">
        <div class="home-card-background" id="jigsaw">
          <div class="card-inner">
            <h3>Huddle</h3>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/programmes.html.erb
<div class="about-banner" id="bluestairs">
</div>
<div class="container text-center text-blue paragraphs">
  <h1 class="text-blue my-4">Programmes</h1>
  <p>Two ‘modules/ programmes’ within our over-arching company profile.</p>
  <p class="m-0"><strong>1. FIRST STEP</strong> Workplace Wellness</p>
  <p class="m-0"><strong>2. HUDDLE</strong> Team Dynamics and Performance</p>
  <img src="<%= asset_path 'oranges.jpg' %>" alt="" class="programmes-image my-5">
  <h2 class="mt-2"> First Step Workplace Wellness</h2>
  <div class=" mt-4">
    <h3 class="mt-0">Abstract</h3>
    <p>The Programme is specifically designed to raise an awareness of how your employee’s health status can affect your bottom line. We specialise in providing information in an informal and interesting setting. We bring an external viewpoint on common pitfalls that contribute towards health-related absenteeism in the workplace. Advice is provided on health management development initiatives that your company can develop internally.</p>
    <h3 class="mt-0">Benefit for CEO/Company</h3>
    <p>There is a two-pronged health issue awaiting businesses in the UK.The UK workforce is an aging workforce that increasingly cannot afford to retire early. Each company will soon have more employees that are motivated to work longer - yet potentially cost the company with a decreased rate of healthiness and accelerated rate of musculoskeletal issues at the workplace. This is where early identification of health and lifestyle interventions can pay huge dividends for those companies that choose to do so.</p>
    <h3 class="mt-0">Benefit for Employee</h3>
    <p>Through a collaborative approach with your employees, we focus on the habits and behaviours that lie behind the workplace activities and traditions within organisations. We aim to instigate minimal changes within employee behaviours which, collectively, can have enormous benefits for employee health and company balance health. Through talks and presentations we target a greater understanding of what each one can do to uplift their workplace health habits, and how this can impact their wellbeing and the company. We aim to inform on how to build healthy resilient employees which have a real world impact on absenteeism and energy and motivation</p>
    <h3 class="mt-0">Did you know…?</h3>
    <p>1. The rate of absenteeism in the UK workforce has fallen from 7.3 days per employee in 1993 to 4.1 in 2018. The ONS statistics in 2017 stated that 77% of workplace absenteeism hours in the UK is now a result of either ill health or musculoskeletal issues, which is up significantly for the 50+ work force. The UK workforce is seemingly getting older, unhealthier yet taking less sick days. Are we expecting a new wave of younger talent to come through and replace those that are brimming with experience? Think again. Professional people younger than 35 have an average job tenure of 19 months. </p>
    <p>2. “Presenteeism- employees going to work even when ill for fear of losing job/pay/project/responsibility.”The workplace sickness rate is falling, but because of an increased pressure internally from employees to attend work. People know that they have measured HR records. Presenteeism may inadvertently lead to a spike in genuine health-related concerns as the workforce ages, as well as an increase in work-related stress.</p>
    <p>3. Statistical research predicts that unless the UK workforce embraces the benefits of healthy lifestyles and physical/mental well-being, many companies will soon be faced with their employees “Running on Fumes” with regards balancing their work-life commitments.</p>
  </div>
  <img src="<%= asset_path 'lightbulb-mobile.jpg' %>" alt="" class="programmes-image my-5">
  <h2 class="mt-2"> Huddle: Team Dynamics and Performance</h2>
  <div class="mt-4">
    <h3 class="mt-0">Abstract</h3>
    <p>The Programme is specifically designed to raise an awareness of the importance of team dynamics, drawing parallels with professional sport where the alignment of vision, strategy and resources make the difference between success and failure. We bring real-world examples of the different modes of coaching and communication in a field where such philosophies determine the difference between the good and the great.</p>
    <h3 class="mt-0">Benefit for CEO/Company</h3>
    <p>This programme highlights the traits of high performing teams and the lessons that can be applied to high performing companies. We also bring leadership lessons drawn from sport, as well as management models used by some of the best coaches in sport and what business can learn from these.</p>
    <h3 class="mt-0">Benefit for Employee</h3>
    <p>This programme is based primarily around the lessons learnt through both success and failure in the sporting world. As a company with significant experience in elite sport in multiple disciplines we pride ourselves on the engagement and interest that we can bring.</p>

  </div>
</div>